### PR TITLE
adding reify at the AST level and fixing rename to work with strong n…

### PR DESCRIPTION
**Pull request by jorgefandinno**
…egation

### CODE REVIEW

**Comment by rkaminsk** [comment]
Just had a quick look. Please undo the changes to `test_reify.py`. We explicitly require the order to be the same as clingo's reify implementation. There was a bug in clingo that introduced compiler specific ordering issues that has been fixed in the latest development version.

**Comment by jorgefandinno** [comment]
> Just had a quick look. Please undo the changes to `test_reify.py`. We explicitly require the order to be the same as clingo's reify implementation. There was a bug in clingo that introduced compiler specific ordering issues that has been fixed in the latest development version.

Done

**Comment by rkaminsk** [comment]
> Before that, one question. Currently, the extra argument of reification always go to the right of the reified object. For instance holds(dead,T). Do you think it make sense to allow them to go both on the right and on the left?

You could generalize by changing the logic so that the function is expected to return the term passed as argument in the resulting sequence.

I'ld probably have added an option how to handle strong negation, that is, whether `-p(X)` is translated as `-holds(p(X))` or as `holds(-p(X))`. In the latter case, one has to add an integrity constraint:
```
:- holds(X), holds(-X).
```
In an encoding you can check if something is not negated using
```
is_atom(X) :- holds(X), X<-X.
```

**Comment by jorgefandinno** [comment]
> > Before that, one question. Currently, the extra argument of reification always go to the right of the reified object. For instance holds(dead,T). Do you think it make sense to allow them to go both on the right and on the left?
> 
> You could generalize by changing the logic so that the function is expected to return the term passed as argument in the resulting sequence.

I made another pull request with this change. Let me know what you think.

> I'ld probably have added an option how to handle strong negation, that is, whether `-p(X)` is translated as `-holds(p(X))` or as `holds(-p(X))`. In the latter case, one has to add an integrity constraint:
> 
> ```
> :- holds(X), holds(-X).
> ```
> 
> In an encoding you can check if something is not negated using
> 
> ```
> is_atom(X) :- holds(X), X<-X.
> ```

Is this documented somewhere? Is it expected to work in the future?

**Comment by rkaminsk** [comment]
> I made another pull request with these changes. Let me know what you think.
> 
> Is this documented somewhere? Is it expected to work in the future?

I think, we should certainly use the extension with the argument function because it gives more flexibility without making the interface more complicated.

With the strong negation suggestion, I was thinking to replace the strong negation name. But this was just a suggestion. If you think that offering the strong negation name is something that is really helpful in practice then we can also add it. If the user wants something very specific than he can use the `rewrite_symbolic_atoms` functions. I think we should decide for one variant to not overload the interface. You can pick which one works better for you.

Regarding the ordering, this always worked. Clingo's ordering considers negated functions larger than non-negated ones.

**Comment by jorgefandinno** [comment]
> > I made another pull request with these changes. Let me know what you think.
> > Is this documented somewhere? Is it expected to work in the future?
> 
> I think, we should certainly use the extension with the argument function because it gives more flexibility without making the interface more complicated.
> 
> With the strong negation suggestion, I was thinking to replace the strong negation name. But this was just a suggestion. If you think that offering the strong negation name is something that is really helpful in practice then we can also add it. If the user wants something very specific than he can use the `rewrite_symbolic_atoms` functions. I think we should decide for one variant to not overload the interface. You can pick which one works better for you.
> 
> Regarding the ordering, this always worked. Clingo's ordering considers negated functions larger than non-negated ones.

I need to think about this. In my case, I need to change the way that strong negation works for eclingo. 
I though to do it with a different name, but may be is just simple to use your method.
I would need is to write

inconsistent(X) :- holds(X), holds(-X).
:- not &K{ not inconsistent(X) }.

which seems elegant.

**Comment by rkaminsk** [comment]
> > > I made another pull request with these changes. Let me know what you think.
> > > Is this documented somewhere? Is it expected to work in the future?
> > 
> > 
> > I think, we should certainly use the extension with the argument function because it gives more flexibility without making the interface more complicated.
> > With the strong negation suggestion, I was thinking to replace the strong negation name. But this was just a suggestion. If you think that offering the strong negation name is something that is really helpful in practice then we can also add it. If the user wants something very specific than he can use the `rewrite_symbolic_atoms` functions. I think we should decide for one variant to not overload the interface. You can pick which one works better for you.
> > Regarding the ordering, this always worked. Clingo's ordering considers negated functions larger than non-negated ones.
> 
> I need to think about this. In my case, I need to change the way that strong negation works for eclingo. I though to do it with a different name, but may be is just simple to use your method. I would need is to write
> 
> inconsistent(X) :- holds(X), holds(-X). :- not &K{ not inconsistent(X) }.
> 
> which seems elegant.

The only problem is that it creates some symmetric rules. To discard them, one would have to add `X < -X`.

**Comment by jorgefandinno** [comment]
> The only problem is that it creates some symmetric rules. To discard them, one would have to add `X < -X`.

Please see the last commit. I adopted this option and and in the documentation how to restore clingo behaviour.
What do you think?

**Comment by rkaminsk** [comment]
> Please see the last commit. I adopted this option and and in the documentation how to restore clingo behaviour.
> What do you think?

It's getting too late here. I'll reply tomorrow.

**Pull request merged**
