### PR TITLE
approximate cautions consequences

### PR DESCRIPTION
**Pull request by jorgefandinno**

### CODE REVIEW

**Comment by rkaminsk** [comment]
I would just call the function approximate and return None if a problem became unsatisfiable.

**Comment by rkaminsk** [comment]
But I already did the changes in my previous commit. :cry:

**Comment by jorgefandinno** [comment]
Sorry, I think I messed it up.

I tried to restore you changes.

Can you check that everything is good now.

**Comment by rkaminsk** [comment]
It's really easy to restore a commit:

```bash
git reset --hard 766d6cecb64dbccc53bce5927515e9a1e6d70034
git push --force
```
As long as git did not cleanup, you can even restore commits that are not in the history (`git reflog` is your friend here).

**Comment by rkaminsk** [comment]
The PR would be okay from my side but maybe you still want to add something.

**Comment by jorgefandinno** [comment]
Thanks, I just added a clarification on returning None. It is now ready on my side

**Pull request merged**
