### PR TITLE
Auto format source code with black

### PR DESCRIPTION
**Pull request by rkaminsk**

### CODE REVIEW

**Comment by rkaminsk** [comment]
@jorgefandinno I would go for this version based on your second proposal. I had a look at the one using pre-commit but did not like it because pre-commit just clones repositories but does not install any dependencies. The latter would be the most useful aspect.

**Comment by jorgefandinno** [comment]
Do you need to pass `${{ secrets.PAT_POTASSCO_BOT }}` to checkout?

This prevents CI to work on forks.

**Comment by rkaminsk** [comment]
@jorgefandinno, no clue where your comment went. It is indeed a problem that the action won't run for collaborators. That's what this is all about after all. Without the secret, the actions won't trigger in the subsequent commits. Now, I am not sure what the best thing to do is. We could just use black as a linter and leave it to the user/local hook script to format the code. Other options would be to use an external service like pre-commit.ci or write an own bot. I don't want anything complicated though...

**Comment by jorgefandinno** [comment]
I moved the comment to review so I point to the line.

I am not sure what do you mean by `subsequent commits`. The ones created automatically?

I wonder if I can just create a secret with the same name and permits in my repository and this would work. If you let me know what permits you put and how to create I can try. We can then document it in the README.

**Comment by rkaminsk** [comment]
> @rkaminsk I moved the comment to review so I point to the line.
> 
> I am not sure what do you mean by `subsequent commits`. The ones created automatically?

For example 794a5c913d207e6263cad264b117b21f89cb1c72 above.

> I wonder if I can just create a secret with the same name and permits in my repository and this would work. If you let me know what permits you put and how to create I can try. We can then document it in the README.

I don't think this will work. To me it looks a bit like the auto formatting won't happen online and there will just be a hook script.

**Comment by jorgefandinno** [comment]
> I don't think this will work. To me it looks a bit like the auto formatting won't happen online and there will just be a hook script.

Why do you think so? For me, does it work when you do a pull-request from inside the same repository? So far, I only checked for pulls. Did you check for pull-requests?

**Comment by rkaminsk** [comment]
> Why do you think so?

Because the secrets of the potassco repository will be used not the ones from your repository.

**Comment by jorgefandinno** [comment]
> I'll remove the auto formatting from the action and use your pre-comment config to run black locally. We'll have to document how to set it up in the readme.

T

> I'll remove the auto formatting from the action and use your pre-comment config to run black locally. We'll have to document how to set it up in the readme.

Wait a second, can you Zoom in?

**Comment by rkaminsk** [comment]
> Wait a second, I got it to work, replacing `token` by `ssh-key`

Be careful. Better do not put *your* private ssh key online. I created a separate account for this experiment. But PAT or SSH, I don't think it matters. The secrets won't be taken from your repository. And even if. We would have to explain to collaborators to set this up first. Which is overkill for things like one-time contributions. A short doc saying you have to:
```bash
python -m pip install pre-commit
pre-commit install
```

Or maybe
```bash
python -m pip install nox
nox
```
to run unit tests and linting is easier.

I'll call it quits for today.

**Comment by jorgefandinno** [comment]
> Be careful. Better do not put _your_ private ssh key online. I created a separate account for this experiment. But PAT or SSH, I don't think it matters.

I created a new ssh key specific for this repository and only has access to it.

> The secrets won't be taken from your repository. 

As I see it, the problem with PAS is depends on the organization name while the SSH secret can have any name. If there is a copy of the secret with this name in each repository it will take the secret for that repository. On a push on my repository takes my secret. On a pull-request from a fork to potassco/python-clingox, it will take the on on potassco.

And even if. We would have to explain to collaborators to set this up first. Which is overkill for things like one-time contributions. A short doc saying you have to:
> 
> ```shell
> python -m pip install pre-commit
> pre-commit install
> ```
> 
> Or maybe
> 
> ```shell
> python -m pip install nox
> nox
> ```
> 
> to run unit tests and linting is easier.
> 
> I'll call it quits for today.

Have you tried without the secret? I tried removing it in my repo and it works without secret just fine.

**Comment by jorgefandinno** [comment]
> @jorgefandinno, this is what I would use after looking at all the options. I also updated the readme. Thanks for helping out with this.

It looks good. Happy to help. Thanks for making the workflow easy.

I am not familiar with nox, yet.

Let us try it for a while and we will see how well it integrates into the workflow.

**Pull request merged**
