### PR TITLE
controlx

### PR DESCRIPTION
**Pull request by jorgefandinno**

### CODE REVIEW

**Comment by rkaminsk** [comment]
This looks like it still needs a lot of work. I'll come back to you with what is required. It might take a while though.

**Comment by rkaminsk** [comment]
I had a first look at the `control.py` file. I would recommend to thin it out a bit. I like having a ground program representation and being able to pretty print it. The symbolic backend might also be nice for writing tests but should be completed. I don't see much added value by the Controlx class; its functions look quite arbitrary. I put some code that is supposed to give a general idea about how to structure things below (I did not touch the symbolic backend but it is rather straight-forward anyway):

```python
from typing import Any, List, NamedTuple, MutableMapping, Sequence
from functools import singledispatch
from itertools import chain

from clingo import Symbol, Function, Observer


@singledispatch
def pretty_str(lit: Any, output_atoms):
    assert "unexpected type"

@pretty_str.register(int)
def _(x: int, output_atoms):
    """
    Pretty print literals and atoms.
    """
    atom = abs(x)
    if atom in output_atoms:
        atom_str = str(output_atoms[atom])
    else:
        atom_str = f"__x{atom}"

    return f"not {atom_str}" if x < 0 else atom_str

# I like the idea of using named tuples for statements because they are rather
# memory efficient.
class Rule(NamedTuple):
    choice: bool
    head: List[int]
    body: List[int]

@pretty_str.register(Rule)
def _(x, output_atoms):
    ret = ""
    if x.choice:
        ret += "{ "
    ret += "; ".join(pretty_str(lit, output_atoms) for lit in x.head)
    if x.choice:
        ret += " }"
    if x.body or (not x.head and not x.choice):
        ret += " :- "
    ret += ", ".join(pretty_str(lit, output_atoms) for lit in x.body)
    ret += "."
    return ret

# This combines the pretty program and program classes and should have some more methods.
class Program:
    output_atoms: MutableMapping[int, Symbol] = {}
    rules: List[Rule] = []

    def __init__(self, output_atoms=None, rules=None):
        self.output_atoms = output_atoms or {}
        self.rules = rules or []

    def __repr__(self):
        return f"Program(output_atoms={repr(self.output_atoms)}, rules={repr(self.rules)})"

    def __str__(self):
        return "\n".join(pretty_str(stm, self.output_atoms) for stm in chain(
            # advanced sorting can be implemented here
            sorted(self.rules)))

class ProgramObserver(Observer):
    def __init__(self, program):
        self._program = program

    def output_atom(self, symbol: Symbol, atom: int) -> None:
        # TODO: facts have to be handled nicely
        self._program.output_atoms[atom] = symbol

    def rule(self, choice: bool, head: Sequence[int], body: Sequence[int]) -> None:
        # categorization of rules can be handled here
        # there can then be a property than returns the chained rules
        self._program.rules.append(Rule(choice, list(head), list(body)))


prg = Program()
obs = ProgramObserver(prg)
obs.output_atom(Function("a"), 1)
obs.output_atom(Function("b"), 2)
obs.output_atom(Function("c"), 3)
obs.rule(False, [1], [2, -3])
print(repr(prg))
print(prg)
```

**Comment by jorgefandinno** [comment]
I think that there are some places where OO constructs are not used properly.
For example the Controlx class should really inherit form Control because it extends its functionality and can be used wherever a Control object is used usually.

This was my original idea, but clingo Application.main gives you an alrady initialitized Control object that you want to wrap around. If you inherit from Control, I don't know how to implement it. Either I get the parent copy unused or I would need to change the parent state which I don't know how to access.

**Comment by jorgefandinno** [comment]
I added some extra functionality for minimize, project and external. Please look into "test_program_observers.py" if the format is correct. I also have a couple of doubts

- Are names starting with "__" reserved in clingo?
- Usually, for each fact in the program the observer registers an unamed fact. It will be nice to remove those facts as only add confusion. Can always be removed safely?

**Comment by jorgefandinno** [comment]
I got the following error

$mypy -p program_observers
/home/fandinno/miniconda3/lib/python3.8/site-packages/clingo/__init__.pyi:20: error: invalid syntax
Found 1 error in 1 file (checked 1 source file)

def parse_files(Iterable[str] files, callback: Callable[[ast.AST], None], logger: Callable[[MessageCode,str],None]=None, message_limit: int=20) -> None: ...

"Iterable[str] files" should be "files: Iterable[str]"?

**Comment by rkaminsk** [comment]
Do you still want to add the `SymbolicBackend`? I do not know what your use case was? Testing maybe? Otherwise, I noted that there is no pretty printing for heuristic statements and they are not added to the program. The library should handle each and every part of a program. But don't worry, I can take care of this.

> > I think that there are some places where OO constructs are not used properly. For example the Controlx class should really inherit form Control because it extends its functionality and can be used wherever a Control object is used usually.
> This was my original idea, but clingo Application.main gives you an already initialitized Control object that you want to wrap around. If you inherit from Control, I don't know how to implement it. Either I get the parent copy unused or I would need to change the parent state which I don't know how to access.

It might be possible to create such an object. Python's object layout is very flexible and objects can be modified at runtime. C extension types behave a bit differently though. But I think in this case it is not a good idea anyway. By providing classes that can be used in conjunction with the control object, we get a very flexible library. Sure, if we want to use all of the features at the same time, we might save a few lines of code with the previous solution. But if we only need part of the functionality, then we save a lot of objects that would just hang around.

> I added some extra functionality for minimize, project and external. Please look into "test_program_observers.py" if the format is correct. I also have a couple of doubts
> 1. Are names starting with "__" reserved in clingo?
> 2. Usually, for each fact in the program the observer registers an unamed fact. It will be nice to remove those facts as only add confusion. Can always be removed safely?

1. Names starting with `__` should not be used in instances and most encodings. We are using them by **convention** in meta encodings or auxiliary encodings to have a separate namespace. It is just a convention though.
2. The second point is more tricky. You cannot rely on this in general. It would need additional code to check if they can really be removed. Ideally, clingo would not generate such rules.

> I got the following error [...]

This issue is already fixed in the wip branch but maybe it is not yet available on anaconda. For now, you could just fix the issue by writing `files: Iterable[str]`.

**Comment by jorgefandinno** [comment]
> Do you still want to add the SymbolicBackend? I do not know what your use
> case was? Testing maybe?
>
I will do it later. I think it's better to finish the ground program first.
I am using it because I have to control objects with the same atoms. The
second, I create it from the rules of the first, but I am not sure they
have the same int representation. I could have a mapping between the two
control objects, but using the SymbolicBackend helps abstracting from this
problem.

I think it is also nicer for debug and testing.

> Otherwise, I noted that there is no pretty printing for heuristic
> statements and they are not added to the program. The library should handle
> each and every part of a program. But don't worry, I can take care of this.
>
That would be better as I am not knowledgeable as how those other parts
work.


> I think that there are some places where OO constructs are not used
> properly. For example the Controlx class should really inherit form Control
> because it extends its functionality and can be used wherever a Control
> object is used usually.
> This was my original idea, but clingo Application.main gives you an
> already initialitized Control object that you want to wrap around. If you
> inherit from Control, I don't know how to implement it. Either I get the
> parent copy unused or I would need to change the parent state which I don't
> know how to access.
>
> It might be possible to create such an object. Python's object layout is
> very flexible and objects can be modified at runtime. C extension types
> behave a bit differently though. But I think in this case it is not a good
> idea anyway. By providing classes that can be used in conjunction with the
> control object, we get a very flexible library. Sure, if we want to use all
> of the features at the same time, we might save a few lines of code with
> the previous solution. But if we only need part of the functionality, then
> we save a lot of objects that would just hang around.
>
The reason to create the Controlx object was that I inherited the code from
a student and it was impossible to know whether it was doing what it was
supposed to do or not. By adding the lines

if debug:
   control = Controlx(control)

at the strat, I can now see the content of the control object at any point
of the code with minimal modifications.


> I added some extra functionality for minimize, project and external.
> Please look into "test_program_observers.py" if the format is correct. I
> also have a couple of doubts
>
>    1. Are names starting with "__" reserved in clingo?
>    2. Usually, for each fact in the program the observer registers an
>    unamed fact. It will be nice to remove those facts as only add confusion.
>    Can always be removed safely?
>
>
>    1. Names starting with __ should not be used in instances and most
>    encodings. We are using them by *convention* in meta encodings or
>    auxiliary encodings to have a separate namespace. It is just a convention
>    though.
>
> In eclingo, I rename all atoms in the program by prefixing them with "u_",
then I only need to avoid using auxiliary predicates that start with it. I
think it is safer, thour perhaps more costly. What do you think?


>
>    1. The second point is more tricky. You cannot rely on this in
>    general. It would need additional code to check if they can really be
>    removed. Ideally, clingo would not generate such rules.
>
> What should we do for now? Print them?

**Comment by rkaminsk** [comment]
> Do you still want to add the SymbolicBackend? I do not know what your use case was? Testing maybe?
> I will do it later. I think it's better to finish the ground program first. I am using it because I have to control objects with the same atoms. The second, I create it from the rules of the first, but I am not sure they have the same int representation. I could have a mapping between the two control objects, but using the SymbolicBackend helps abstracting from this problem. I think it is also nicer for debug and testing.

It would also be possible to provide a function that adds the program we already have via a backend. The mapping of arguments could be dealt with with a separate function.
```python
class Program:
    [...]
    def add_to_backend(self, backend: Backend, mapping: Callable[[int], int]) -> None: ...
```
The library can provide ready to use mappings like the identity mapping or a mapping that creates fresh literals.

> The reason to create the Controlx object was that I inherited the code from a student and it was impossible to know whether it was doing what it was supposed to do or not. By adding the lines 
> ```python
> if debug: control = Controlx(control)
> ```
> at the strat, I can now see the content of the control object at any point of the code with minimal modifications.

We can add such at thing but then it should go into a separate debug module. For debugging all kinds of hacks are permitted. :wink: 

> In eclingo, I rename all atoms in the program by prefixing them with "u_",
> then I only need to avoid using auxiliary predicates that start with it. I think it is safer, though perhaps more costly. What do you think?

I do not know how eclingo is implemented but you could also prefix the rules you are writing with `__`. If the user does not use `__` as a prefix, then there can be no clashes. You can of course also use the AST to prefix the users rules to avoid name clashes. Up to you.

**Comment by jorgefandinno** [comment]
>
>
> It would also be possible to provide a function that adds the program we
> already have via a backend. The mapping of arguments could be dealt with
> with a separate function.
>
> class Program:
>
>     [...]
>
>     def add_to_backend(self, backend: Backend, mapping: Callable[[int], int]) -> None: ...
>
> The library can provide ready to use mappings like the identity mapping or
> a mapping that creates fresh literals.
>

How can we ensure that a given atom will have a specific int
representation? Otherwise, we cannot know the mapping before adding the
atoms, right? This was the problem I faced and the reason I added the
SymbolicBackend.


> The reason to create the Controlx object was that I inherited the code
> from a student and it was impossible to know whether it was doing what it
> was supposed to do or not. By adding the lines
>
> if debug: control = Controlx(control)
>
> at the strat, I can now see the content of the control object at any point
> of the code with minimal modifications.
>
> We can add such at thing but then it should go into a separate debug
> module. For debugging all kinds of hacks are permitted. 😉
>
> In eclingo, I rename all atoms in the program by prefixing them with "u_",
> then I only need to avoid using auxiliary predicates that start with it. I
> think it is safer, though perhaps more costly. What do you think?
>
> I do not know how eclingo is implemented but you could also prefix the
> rules you are writing with __. If the user does not use __ as a prefix,
> then there can be no clashes. You can of course also use the AST to prefix
> the users rules to avoid name clashes. Up to you.
>
I have code to do this. If you find it interesting, we can try to make it
more general and available to everybody as well.

**Comment by rkaminsk** [comment]
> How can we ensure that a given atom will have a specific int representation? Otherwise, we cannot know the mapping before adding the atoms, right? This was the problem I faced and the reason I added the SymbolicBackend.

I do not really understand the question. Since the mapping function is an arbitrary callable the user can implement whatever he wants. This might entail some beforehand initialization and/or an internal dictionary.

> I have code to do this. If you find it interesting, we can try to make it more general and available to everybody as well.

It should be trivial to implement with the transformer. Just visit every SymbolicAtom and modify the corresponding function/symbol. We can add a function/transformer.

**Comment by rkaminsk** [comment]
I did a cleanup/bugfix pass without implementing (much) new stuff. If you give me access to your repository, I could push the changes myself. With this patch, unit tests will fail but are easy to fix. It has also not reached the final state yet.
```patch
diff --git a/clingox/program_observers.py b/clingox/program_observers.py
index b560062..c6aae62 100644
--- a/clingox/program_observers.py
+++ b/clingox/program_observers.py
@@ -1,20 +1,38 @@
-from typing import Any, Iterable, List, NamedTuple, MutableMapping, Sequence, Tuple
+'''
+This module provides functions to work with ground programs.
+
+This includes construting a ground representation using an observer, pretty
+printing the ground representation, and adding ground program to control
+objects via the backend.
+'''
+
+from typing import Any, List, Mapping, MutableMapping, NamedTuple, Sequence, Tuple, Union
 from dataclasses import dataclass, field
 from functools import singledispatch
 from itertools import chain
+from textwrap import dedent
 
 from clingo import HeuristicType, Symbol, Observer, TruthValue
 
+Atom = int
+Literal = int
+Weight = int
+OutputTable = Mapping[int, Symbol]
+
 
 @singledispatch
-def pretty_str(lit: Any, output_atoms): # pylint: disable=unused-argument
-    assert "unexpected type" # pylint: disable=assert-on-string-literal
+def pretty_str(arg: Any, output_atoms: OutputTable): # pylint: disable=unused-argument
+    '''
+    Pretty print program constructs.
+    '''
+    assert False, "unexpected type"
+
 
 @pretty_str.register
-def _(arg: int, output_atoms):
-    """
-    Pretty printliterals and atoms.
-    """
+def _pretty_str_lit(arg: Literal, output_atoms: OutputTable):
+    '''
+    Pretty print literals and atoms.
+    '''
     atom = abs(arg)
     if atom in output_atoms:
         atom_str = str(output_atoms[atom])
@@ -23,21 +41,71 @@ def _(arg: int, output_atoms):
 
     return f"not {atom_str}" if arg < 0 else atom_str
 
+@pretty_str.register(TruthValue)
+def _pretty_str_truth_value(arg: TruthValue, output_atoms: OutputTable):
+    '''
+    Pretty print a truth value.
+    '''
+    if arg == TruthValue.False_:
+        return "False"
+    if arg == TruthValue.True_:
+        return "True"
+    return "Free"
+
+
+class Fact(NamedTuple):
+    '''
+    Ground representation of a fact.
+    '''
+    symbol: Symbol
+
+@pretty_str.register
+def _pretty_str_fact(arg: Fact, output_atoms: OutputTable): # pylint: disable=unused-argument
+    '''
+    Pretty print a fact.
+    '''
+    return f"{arg.symbol}"
+
+
+class Show(NamedTuple):
+    '''
+    Ground representation of a show statements.
+    '''
+    symbol: Symbol
+    condition: Sequence[Literal]
+
+@pretty_str.register
+def _pretty_str_show(arg: Show, output_atoms: OutputTable):
+    '''
+    Pretty print a fact.
+    '''
+    body = ', '.join(pretty_str(lit, output_atoms) for lit in arg.condition)
+    return f'#show {arg.symbol}{": " if body else ""}{body}.'
+
 
 class Rule(NamedTuple):
+    '''
+    Ground representation of disjunctive and choice rules.
+    '''
     choice: bool
-    head: List[int]
-    body: List[int]
+    head: Sequence[Atom]
+    body: Sequence[Literal]
 
 class WeightRule(NamedTuple):
+    '''
+    Ground representation of rules with a weight constraint in the body.
+    '''
     choice: bool
-    head: Sequence[int]
-    lower_bound: int
-    body: Sequence[Tuple[int, int]]
+    head: Sequence[Atom]
+    lower_bound: Weight
+    body: Sequence[Tuple[Literal, Weight]]
 
 @pretty_str.register(Rule)
 @pretty_str.register(WeightRule)
-def _(arg, output_atoms):
+def _pretty_str_rule(arg: Union[Rule, WeightRule], output_atoms: OutputTable):
+    '''
+    Pretty print a rule or weight rule.
+    '''
     ret = ""
     if arg.choice:
         ret += "{"
@@ -48,116 +116,226 @@ def _(arg, output_atoms):
         ret += " :- "
 
     if isinstance(arg, WeightRule):
-        body = ", ".join(str(x[1]) + ":" + pretty_str(x[0], output_atoms) for x in arg.body)
-        ret += str(arg.lower_bound) + "{" + body + "}"
+        body = ", ".join(f'{weight},{i}: {pretty_str(literal, output_atoms)}'
+                         for i, (literal, weight) in enumerate(arg.body))
+        ret += f'{arg.lower_bound}{{{body}}}'
     else:
         ret += ", ".join(pretty_str(lit, output_atoms) for lit in arg.body)
     ret += "."
     return ret
 
+
 class Project(NamedTuple):
-    atoms: Sequence[int]
+    '''
+    Ground representation of project statements.
+    '''
+    atoms: Sequence[Atom]
 
 @pretty_str.register(Project)
-def _(arg, output_atoms):
-    atoms = ','.join(pretty_str(atom, output_atoms) for atom in arg.atoms)
-    if atoms:
-        return '#project ' + atoms  + '.'
-    else:
-        return '#project.'
+def _pretty_str_project(arg: Project, output_atoms: OutputTable):
+    '''
+    Pretty print a project statement.
+    '''
+    atoms = ', '.join(pretty_str(atom, output_atoms) for atom in arg.atoms)
+    return f'#project{" " if atoms else ""}{atoms}.'
+
 
 class External(NamedTuple):
-    atom: int
+    '''
+    Ground representation of external atoms.
+    '''
+    atom: Atom
     value: TruthValue
 
-@pretty_str.register(TruthValue)
-def _(arg, output_atoms):
-    if arg == TruthValue.False_:
-        return "False"
-    elif arg == TruthValue.True_:
-        return "True"
-    else:
-        return str(arg)
-
 @pretty_str.register(External)
-def _(arg, output_atoms):
-    return f"#external {pretty_str(arg.atom, output_atoms)}. % value={pretty_str(arg.value, output_atoms)}"
+def _pretty_print_external(arg: External, output_atoms: OutputTable):
+    '''
+    Pretty print an external.
+    '''
+    return f"#external {pretty_str(arg.atom, output_atoms)}. [{pretty_str(arg.value, output_atoms)}]"
+
 
 class Minimize(NamedTuple):
-    priority: int
-    literals: Iterable[Tuple[int,int]]
+    '''
+    Ground representation of a minimize statement.
+    '''
+    priority: Weight
+    literals: Sequence[Tuple[Literal, Weight]]
 
 @pretty_str.register(Minimize)
-def _(arg, output_atoms):
-    body = ((pretty_str(x[0], output_atoms),x[1]) for x in arg.literals)
-    body = "; ".join(f"{x[1]}@{arg.priority},{x[0]}:{x[0]}" for x in body)
+def _pretty_print_minimize(arg, output_atoms):
+    '''
+    Pretty print a minimize statement.
+    '''
+    body = "; ".join(f"{weight}@{arg.priority},{i}: {pretty_str(literal, output_atoms)}"
+                     for i, (literal, weight) in enumerate(arg.literals))
     return f"#minimize{{{body}}}."
 
+
 class Heuristic(NamedTuple):
-    atom: int
+    '''
+    Ground representation of a heuristic statement.
+    '''
+    atom: Atom
     type_: HeuristicType
-    bias: int
-    priority: int
-    condition: Iterable[int]
+    bias: Weight
+    priority: Weight
+    condition: Sequence[Literal]
+
+@pretty_str.register(Heuristic)
+def _pretty_str_heuristic(arg: Heuristic, output_atoms: OutputTable):
+    '''
+    Pretty print a heuristic statement.
+    '''
+    body = ', '.join(pretty_str(lit, output_atoms) for lit in arg.condition)
+    return f'#heuristic {arg.atom}{": " if body else ""}{body}. [{arg.bias}@{arg.priority}, {arg.type_}]'
+
+
+class Edge(NamedTuple):
+    '''
+    Ground representation of a heuristic statement.
+    '''
+    u: int
+    v: int
+    condition: Sequence[Literal]
+
+@pretty_str.register(Edge)
+def _pretty_str_edge(arg: Edge, output_atoms: OutputTable):
+    '''
+    Pretty print a heuristic statement.
+    '''
+    body = ', '.join(pretty_str(lit, output_atoms) for lit in arg.condition)
+    return f'#edge ({arg.u},{arg.v}){": " if body else ""}{body}.'
+
 
 class Assume(NamedTuple):
-    literals: Iterable[int]
+    '''
+    Ground representation of an assume statement.
+    '''
+    literals: Sequence[Literal]
+
+@pretty_str.register(Assume)
+def _pretty_str_assume(arg: Assume, output_atoms: OutputTable):
+    '''
+    Pretty print a assume statement.
+    '''
+    body = ', '.join(pretty_str(lit, output_atoms) for lit in arg.literals)
+    return f'#assume{" " if body else ""}{body}.'
+
 
-# This combines the pretty program and program classes and should have some more methods.
 @dataclass
-class Program:
+class Program: # pylint: disable=too-many-instance-attributes
+    '''
+    Ground program representation.
+
+    Although inefficient, the string representation of this program is parsable
+    by clingo.
+    '''
     output_atoms: MutableMapping[int, Symbol] = field(default_factory=dict)
-    facts: List[Rule] = field(default_factory=list)
+    shows: List[Show] = field(default_factory=list)
+    facts: List[Fact] = field(default_factory=list)
     rules: List[Rule] = field(default_factory=list)
-    minimizes: List[Rule] = field(default_factory=list)
-    projects: List[Rule] = field(default_factory=list)
-    externals: List[Rule] = field(default_factory=list)
+    weight_rules: List[WeightRule] = field(default_factory=list)
+    heuristics: List[Heuristic] = field(default_factory=list)
+    edges: List[Edge] = field(default_factory=list)
+    minimizes: List[Minimize] = field(default_factory=list)
+    externals: List[External] = field(default_factory=list)
+    projects: List[Project] = field(default_factory=list)
+    assumes: List[Assume] = field(default_factory=list)
 
     def __repr__(self):
-        return f"""Program(output_atoms={repr(self.output_atoms)},
-                           rules={repr(self.rules)}, 
-                           minimizes={repr(self.minimizes)},
-                           projects={repr(self.projects)},
-                           externals={repr(self.externals)},
-                          )"""
+        return dedent(f'''\
+            Program(output_atoms={repr(self.output_atoms)},
+                    shows={repr(self.shows)},
+                    facts={repr(self.facts)},
+                    rules={repr(self.rules)},
+                    weight_rules={repr(self.rules)},
+                    heuristics={repr(self.heuristics)},
+                    edges={repr(self.edges)},
+                    minimizes={repr(self.minimizes)},
+                    externals={repr(self.externals)},
+                    projects={repr(self.projects)},
+                    assumes={repr(self.assumes)})''')
 
     def __str__(self):
-        ret = "\n".join(f"{stm}." for stm in sorted(self.facts))
-        if ret:
-            ret += "\n"
-        ret += "\n".join(pretty_str(stm, self.output_atoms) for stm in chain(
-            # advanced sorting can be implemented here
+        return "\n".join(pretty_str(stm, self.output_atoms) for stm in chain(
+            sorted(self.shows),
+            sorted(self.facts),
             sorted(self.rules),
+            sorted(self.weight_rules),
+            sorted(self.heuristics),
+            sorted(self.edges),
             sorted(self.minimizes),
+            sorted(self.externals),
             sorted(self.projects),
-            sorted(self.externals)
-            ))
-        return ret
+            sorted(self.assumes)))
+
 
 class ProgramObserver(Observer):
-    def __init__(self, program):
+    '''
+    Program observer to build a ground program representation while grounding.
+
+    This class explicitly ignores theory atoms because they already have a
+    ground representation.
+    '''
+    _program: Program
+
+    def __init__(self, program: Program):
         self._program = program
 
+    def begin_step(self) -> None:
+        '''
+        Resets the assumptions.
+        '''
+        self._program.assumes.clear()
+
     def output_atom(self, symbol: Symbol, atom: int) -> None:
+        '''
+        Add the given atom to the list of facts or output table.
+        '''
         if atom != 0:
             self._program.output_atoms[atom] = symbol
         else:
-            self._program.facts.append(symbol)
+            self._program.facts.append(Fact(symbol))
 
+    def output_term(self, symbol: Symbol, condition: Sequence[int]) -> None:
+        '''
+        Add a term to the output table.
+        '''
+        self._program.shows.append(Show(symbol, condition))
 
     def rule(self, choice: bool, head: Sequence[int], body: Sequence[int]) -> None:
-        # categorization of rules can be handled here
-        # there can then be a property than returns the chained rules
-        self._program.rules.append(Rule(choice, list(head), list(body)))
+        '''
+        Add a rule to the ground representation.
+        '''
+        self._program.rules.append(Rule(choice, head, body))
 
     def weight_rule(self, choice: bool, head: Sequence[int], lower_bound: int, body: Sequence[Tuple[int, int]]) -> None:
-        self._program.rules.append(WeightRule(choice, list(head), lower_bound, list(body)))
+        '''
+        Add a weight rule to the ground representation.
+        '''
+        self._program.weight_rules.append(WeightRule(choice, head, lower_bound, body))
 
     def project(self, atoms: Sequence[int]) -> None:
+        '''
+        Add a project statement to the ground representation.
+        '''
         self._program.projects.append(Project(atoms))
 
     def external(self, atom: int, value: TruthValue) -> None:
+        '''
+        Add an external statement to the ground representation.
+        '''
         self._program.externals.append(External(atom, value))
 
-    def minimize(self, priority: int, literals: Sequence[Tuple[int,int]]) -> None:
-        self._program.minimizes.append(Minimize(priority, list(literals)))
+    def minimize(self, priority: int, literals: Sequence[Tuple[int, int]]) -> None:
+        '''
+        Add a minimize statement to the ground representation.
+        '''
+        self._program.minimizes.append(Minimize(priority, literals))
+
+    def acyc_edge(self, node_u: int, node_v: int, condition: Sequence[int]) -> None:
+        '''
+        Add an edge statement to the gronud representation.
+        '''
+        self._program.edges.append(Edge(node_u, node_v, condition))
```

**Comment by jorgefandinno** [comment]
Done. I added to the repository.

By the way, did you try before? I understood that when you do a pull
request to another repository the administrator of that repository gets
access to yours.
Did not work?

**Comment by rkaminsk** [comment]
> Done. I added to the repository. By the way, did you try before? I understood that when you do a pull request to another repository the administrator of that repository gets access to yours. Did not work?

I tried. It did not work. It might be an extra setting.

**Comment by jorgefandinno** [comment]
> > How can we ensure that a given atom will have a specific int representation? Otherwise, we cannot know the mapping before adding the atoms, right? This was the problem I faced and the reason I added the SymbolicBackend.
> 
> I do not really understand the question. Since the mapping function is an arbitrary callable the user can implement whatever he wants. This might entail some beforehand initialization and/or an internal dictionary.

Ok and initialization may do the job. Then, we need to functions

def add_output_atoms_to_backend(self, backend: Backend) -> Callable[[int], int]): ...
def add_rules_to_backend(self, backend: Backend, mapping: Callable[[int], int]) -> None: ...

where the first adds the output atoms and returns the mapping to use by the second.
We can also have a function that does all in one step

def add_to_backend(self, backend: Backend, mapping: Callable[[int], int]) -> Callable[[int], int]):
    mapping = self.add_output_atoms_to_backend(backend) -> Callable[[int], int])
    self.add_rules_to_backend(backend, mapping)
    return mapping

**Comment by rkaminsk** [comment]
> def add_output_atoms_to_backend(self, backend: Backend) -> Callable[[int], int]): ...
> def add_rules_to_backend(self, backend: Backend, mapping: Callable[[int], int]) -> None: ...

The code below might do what you have in mind and also handles auxiliary literals gracefully. It is of course also possible to implement this with the functions above but I like to use a class to emphasize that there is state behind the scenes.

```python
# maybe something more clever to also handle signs
class Remapping:
  def __init__(self, backend: Backend, output_atoms: OutputTable):
    self._backend = backend
    self._map = {}
    for lit, sym in output_atoms.items():
      assert lit not in self._map
      self._map[lit] = self._backend.add_atom(sym)

  def __call__(self, lit: Literal) -> Literal:
    if lit not in self._map:
      self._map[lit] = self._backend.add_atom()
    return self._map[lit]
```

**Comment by jorgefandinno** [comment]
Yes, that looks good to me.
We can add the following to consider signs

# maybe something more clever to also handle signs
class Remapping:
  def __init__(self, backend: Backend, output_atoms: OutputTable):
    self._backend = backend
    self._map = {}
    for lit, sym in output_atoms.items():
      assert lit not in self._map
      self._map[lit] = self._backend.add_atom(sym)

  def __remap_atom(self, atom: Atom) -> Atom:
    if atom not in self._map:
      self._map[atom] = self._backend.add_atom()
    return self._map[atom]

def __call__(self, lit: Literal) -> Literal:
    if lit >= 0:
        return self.__remap_atom(lit)
    return -self.__remap_atom(-lit)

Maybe we can also add functions to remap the rest of objects too.
What do you think?

**Comment by jorgefandinno** [comment]
def remap(self, mapping: LiteralMap) -> 'Program':

should this adhere to (https://en.wikipedia.org/wiki/Command%E2%80%93query_separation)

**Comment by rkaminsk** [comment]
> def remap(self, mapping: LiteralMap) -> 'Program':
> 
> should this adhere to (https://en.wikipedia.org/wiki/Command%E2%80%93query_separation)

The signature might confuse a functional programmer. But it's a convenience thing. With this one can write:
```python
prg.remap(mapping).add_to_backend(backend)
```
But one has to be careful because the program is modified in place.

We could also make the functions side-effect free but then memory can only be reclaimed at the end.

In terms of releasing memory early the function could also be improved by writing:
```python
for i, x in enumerate(l):
    l[i] = remap(x)
```

**Comment by rkaminsk** [comment]
I am not sure about the ASTInspector class yet. I am sure that I do not like it in its current form. For now I will just put it into a seperate branch and make up my mind later to get this PR done with. I'll add the remaining unit tests next.

**Comment by rkaminsk** [comment]
Still not finished but now it's just the test cases for the remapping that are left.

**Comment by rkaminsk** [comment]
@jorgefandinno I am done here. Can you have a look? If you are fine with this I would merge and we can rebase your other PRs on this.

**Pull request merged**
