### PR TITLE
Jorge/filter body

### PR DESCRIPTION
**Pull request by jorgefandinno**
I replaced the function in eclingo already and looks cleaner.

Let me know if you have suggestions about the name.

### CODE REVIEW

**Comment by rkaminsk** [comment]
Please have a look if this works for you.

**Comment by jorgefandinno** [comment]
> Please have a look if this works for you.

It works. Also I find that pip can install from github, so now I can directly test in eclingo as well!

**Comment by rkaminsk** [comment]
Should I merge or wait for feedback?

**Comment by jorgefandinno** [comment]
> Should I merge or wait for feedback?

Feedback from whom?

From my side, it is ready to merge.
The current version of eclingo is already linked to this branch. Once is merged, I will just change the dependency.

Code looks good and all test are passing there.

**Pull request merged**
