### PR TITLE
Add function to get body literals.

### PR DESCRIPTION
**Pull request by jorgefandinno**
test_asp.py became too long 1050/1000 lines

I added "# pylint: disable=too-many-lines"

We also can split it in two.

Let me know what do you prefer.

### CODE REVIEW

**Comment by rkaminsk** [comment]
> test_asp.py became too long 1050/1000 lines
> 
> I added "# pylint: disable=too-many-lines"
> 
> We also can split it in two.
> 
> Let me know what do you prefer.

I don't mind so much if a module is a bit longer. I also don't see a good way to cut it here. We can simply increase the limit in the global `.pylintrc` to say 2000.

Currently, the function would also collect elements in other statements than rules, for example, `#show statements`.

The function `get_positive_body` should be added to `__ALL__`. Maybe make the `PositiveBodyVisitor` private. The case for the rule could be removed and we could simply call `visit(stm.body)` assuming `stm` is the `AST` argument of `get_positive_body`.

We can also make the function more general and maybe not call it `get_positive_body` (which is questionable with antimonotone aggregates for example). What about the following:
```python
get_body(stm: AST, 
         exclude_aggregates: bool = False,
         exclude_theory_atoms: bool = False,
         exclude_signs: Tuple[Sign] = ())
```
I also like exclude better than discard.

**Comment by jorgefandinno** [comment]
It makes sense. I made the changes you suggested.

I also include the option to exclude conditional literals and use a Container instead of a Tuple for exclude_signs.

**Comment by rkaminsk** [comment]
> It makes sense. I made the changes you suggested.
> 
> I also include the option to exclude conditional literals and use a Container instead of a Tuple for exclude_signs.

Cool, I have a look at this one next. But now its weekend!!! :smile:

**Comment by rkaminsk** [comment]
I did a couple of things:

- removed the visitor because there was no recursive visiting happening,
- adjusted docstrings,
- removed remaining occurrences of "positive body",
- update the pylintrc to work with the latest pylint version.

The PR is fine from my side.

**Comment by jorgefandinno** [comment]
I just updated the docstring.

It seems that pylint complains about an unrelated function "evaluate_binary()".

**Comment by rkaminsk** [comment]
> I just updated the docstring.
> 
> On my computer pylint complains about "evaluate_binary()" and "evaluate_unary()":
> 
> clingox/theory.py:132:4: R0201: Method could be a function (no-self-use) clingox/theory.py:171:4: R0201: Method could be a function (no-self-use)

This seems to be checked by an extension: <https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/no-self-use.html>. I don't know why it is enabled on your computer.

**Pull request merged**
